Gestion de membres: tx_ligestmembrelabo_pi1 Class Reference
tx_ligestmembrelabo_pi1 Class Reference
Public Member Functions
main ($content, $conf)
Public Attributes
$prefixId = 'tx_ligestmembrelabo_pi1'
$scriptRelPath = 'pi1/class.tx_ligestmembrelabo_pi1.php'
$extKey = 'li_gest_membre_labo'
$pi_checkCHash = true
Private Member Functions
rechercheFils ($pid_parent)
rechercherUidLangue ($uid, $sys_language_uid, $uid_parent, $texte_champ, $table, $nom_champ)
equipe ($uid_equipes, $typeDate)
typeDePoste ($typeDePoste, $typeDate)
categorie ($uid_categories, $typeDate)
structure ($uid_structures, $typeDate)
rechercheStructuresFille ($id_parent)
fonction ($uid_fonctions, $typeDate)
diplome ($uid_diplomes)
Detailed Description
Definition at line 56 of file class.tx_ligestmembrelabo_pi1.php.
Member Function Documentation
tx_ligestmembrelabo_pi1::rechercheFils ($ pid_parent) [private]
Recherche des sous-dossiers contenant les membres du laboratoire...
Parameters:
$pid_parent identifiant du dossier à explorer
Returns:
Un tableau contenant tous les sous-dossiers trouvés...
Definition at line 67 of file class.tx_ligestmembrelabo_pi1.php.
Referenced by main().
tx_ligestmembrelabo_pi1::rechercherUidLangue ($ uid, $ sys_language_uid, $ uid_parent, $ texte_champ, $ table, $ nom_champ) [private]
Gestion du multilangue Cette fonction recherche le texte le plus approprié par rapport à la page chargée Cette fonction est utilisée à la suite d'une requête permettant de connaître les paramètres $uid, $sys_language_uid, $uid_parent et $texte_champ.
Parameters:
$uid L'identifiant de l'enregistrement pour lequel on recherche la meilleur traduction.
$sys_language_uid L'identifiant de la langue de l'enregistrement pour lequel on recherche la meilleur traduction.
$uid_parent L'identifiant du parent de l'enregistrement pour lequel on recherche la meilleur traduction.
$texte_champ La traduction de l'enregistrement pour lequel on recherche la meilleur traduction.
$table Le nom de la table dans laquel se trouve le champ à traduire
$nom_champ Le nom du champ à traduire
Returns:
Une chaîne de caratères contenant la traduction a afficher
Definition at line 118 of file class.tx_ligestmembrelabo_pi1.php.
Referenced by main().
tx_ligestmembrelabo_pi1::equipe ($ uid_equipes, $ typeDate) [private]
Choix de l'équipe Cette fonction permet de créer une contrainte concernant le type de poste
Parameters:
$equipe Chaîne de caractères contenant les identifiants des équipes(uid) séparés par des virgules
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 188 of file class.tx_ligestmembrelabo_pi1.php.
Referenced by main().
tx_ligestmembrelabo_pi1::typeDePoste ($ typeDePoste, $ typeDate) [private]
Choix du type de poste Cette fonction permet de créer une contrainte concernant le type de poste
Parameters:
$typeDePoste Chaîne de caractères contenant les identifiants des types de poste (uid) séparés par des virgules
$typeDate Chaîne de caractère contenant le type de date: Actuels, Anciens ou Tous
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 242 of file class.tx_ligestmembrelabo_pi1.php.
Referenced by main().
tx_ligestmembrelabo_pi1::categorie ($ uid_categories, $ typeDate) [private]
Choix des categories Cette fonction permet de créer une contrainte concernant les categories
Parameters:
$uid_categories Chaîne de caractères contenant les identifiants des catégories (uid) séparés par une virgule
$typeDate Chaîne de caractère contenant le type de date: Actuels, Anciens ou Tous
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 293 of file class.tx_ligestmembrelabo_pi1.php.
Referenced by main().
tx_ligestmembrelabo_pi1::structure ($ uid_structures, $ typeDate) [private]
Choix des structures Cette fonction permet de créer une contrainte concernant les structures
Parameters:
$uid_categories Chaîne de caractères contenant les identifiants des structures (uid) séparés par une virgule
$typeDate Chaîne de caractère contenant le type de date: Actuels, Anciens ou Tous
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 344 of file class.tx_ligestmembrelabo_pi1.php.
References rechercheStructuresFille().
Referenced by main().
tx_ligestmembrelabo_pi1::rechercheStructuresFille ($ id_parent) [private]
Recherche de structures filles
Parameters:
$id_parent identifiant de la structure principale
Returns:
Un tableau contenant toutes les sous-structures trouvées...
Definition at line 406 of file class.tx_ligestmembrelabo_pi1.php.
Referenced by structure().
tx_ligestmembrelabo_pi1::fonction ($ uid_fonctions, $ typeDate) [private]
Choix des fonctions Cette fonction permet de créer une contrainte concernant les fonctions
Parameters:
$uid_fonctions Chaîne de caractères contenant les identifiants des fonctions (uid) séparés par une virgule
$typeDate Chaîne de caractère contenant le type de date: Actuels, Anciens ou Tous
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 455 of file class.tx_ligestmembrelabo_pi1.php.
Referenced by main().
tx_ligestmembrelabo_pi1::diplome ($ uid_diplomes) [private]
Choix des diplomes Cette fonction permet de créer une contrainte concernant les diplomes
Parameters:
$uid_diplomes Chaîne de caractères contenant les identifiants des diplômes (uid) séparés par une virgule
Returns:
Une chaîne de caratères contenant une contrainte à rajouter à une requête
Definition at line 504 of file class.tx_ligestmembrelabo_pi1.php.
Referenced by main().
tx_ligestmembrelabo_pi1::main ($ content, $ conf)
The main method of the PlugIn
Parameters:
string $content: The PlugIn content
array $conf: The PlugIn configuration
Returns:
The content that is displayed on the website
Definition at line 544 of file class.tx_ligestmembrelabo_pi1.php.
References categorie(), diplome(), equipe(), fonction(), rechercheFils(), rechercherUidLangue(), structure(), and typeDePoste().
Member Data Documentation
tx_ligestmembrelabo_pi1::$prefixId = 'tx_ligestmembrelabo_pi1'
Definition at line 57 of file class.tx_ligestmembrelabo_pi1.php.
tx_ligestmembrelabo_pi1::$scriptRelPath = 'pi1/class.tx_ligestmembrelabo_pi1.php'
Definition at line 58 of file class.tx_ligestmembrelabo_pi1.php.
tx_ligestmembrelabo_pi1::$extKey = 'li_gest_membre_labo'
Definition at line 59 of file class.tx_ligestmembrelabo_pi1.php.
tx_ligestmembrelabo_pi1::$pi_checkCHash = true
Definition at line 60 of file class.tx_ligestmembrelabo_pi1.php.
The documentation for this class was generated from the following file:
U:/Typo3/svn/trunk/li_gest_membre_labo/pi1/class.tx_ligestmembrelabo_pi1.php